# Generated by Django 3.0.8 on 2020-07-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
