# Generated by Django 3.0.8 on 2020-07-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noveluser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
