# Generated by Django 3.0.8 on 2020-07-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_noveluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noveluser',
        ),
    ]
