# Generated by Django 3.0.8 on 2020-08-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_books'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
    ]
